version: 1.0
provider:
  name: openfaas
  gateway: https://gateway.ofc.do.controlplane.info
functions:
  goto:
    lang: node10-express
    handler: ./goto
    image: registry.digitalocean.com/do-very-good/goto:latest

