version: 1.0
provider:
  name: openfaas
  gateway: https://gateway.ofc.do.controlplane.info
functions:
  goto:
    lang: node12
    handler: ./goto
    image: registry.digitalocean.com/do-good-images/goto:latest

